CREATE TABLE user_admin (
    id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(20) NOT NULL,
    userlevel VARCHAR(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;